config/routes.rb
Bootstrappedapp::Application.routes.draw do

  resources :sessions, only: [:create, :new, :destroy]

  resources :users

  get "home/homepage"

  get "home/help"

  get "home/about_us"

  resources :recipes

  resources :categories

  match "/signup", to: "users#new"

  match "/signin", to: "sessions#new"

  match "/signout", to: "sessions#destroy"

  root :to => 'home#homepage'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def homepage
  	@categories = Category.all
  	@recipes = Recipe.all
  end

  def help
  end

  def about_us
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_about_us.html.erb
<h1>Home#about_us</h1>
<p>Find me in app/views/home/about_us.html.erb</p>

app/views/home/_help.html.erb
<h1>Home#help</h1>
<p>Find me in app/views/home/help.html.erb</p>

app/views/home/_homepage.html.erb
	<ul class="nav nav-pills">
		<li class="active"><a href="#tab1" data-toggle="tab"><i class="icon-home"></i>Home</a></li>
		<li><a href="#tab2" data-toggle="tab">Help</a></li>
		<li><a href="#tab3" data-toggle="tab">About us</a></li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane active" id="tab1">
			<%= render 'home/mainpage' %>
		</div>

		<div class="tab-pane fade" id="tab2">
			<%= render "home/help" %>
		</div>

		<div class="tab-pane fade" id="tab3">
			<%= render "home/about_us" %>
		</div>
	</div>

app/views/home/_mainpage.html.erb
<div class="center hero-unit">
	<h1>Recipe Book</h1>
	<h2>Learn how to cook and prepare delicious meals in no time!</h2>
</div>
<div class="row-fluid">
	<% if signed_in? %>
	<div class="span2">
		<ul class="nav nav-list">
			<li class="nav-header"><i class="icon-list"></i>Menu</li>
				<li><%= link_to "Create new Category", new_category_path %></li>
			
				<li><%= link_to "Create new Recipe", new_recipe_path %></li>
		</ul>
	</div>

	<% else %>
	<div class="span2">
		<div class="btn-group">
			<a class="btn btn-info" href="#"><i class="icon-user icon-white"></i></a>
		<%= link_to "Signin", new_session_path, class: "btn btn-info" %>
	</div>
	</div>
	<% end %>
	<div class="span5">
		<h2>List of categories available: </h2><br />
		<% @categories.each do |categories| %>
			<table class="table table-hover">
				<tbody>
				<tr>
					<td><%= link_to categories.name, categories %></td>
				</tr>
			</tbody>
			</table>
		<% end %>
	</div>
	<div class="span5">
		<h2><%= link_to "List of all available recipes:", recipes_path %></h2><br />
		<table class="table table-hover">
			<caption>List of all available recipes</caption>
			<thead>
			<tr>
				<th>Recipe Name</th>
				<th>Category</th>
			</tr>
		</thead>
		<tbody>
			<% @recipes.each do |recipes| %>
				<tr>
					<td><%= link_to recipes.name, recipes %></td>
					<td><%= recipes.category.name %></td>
				</tr>
			<% end %>
		</tbody>
			</table>
	</div>
</div>

app/views/home/homepage.html.erb
<%= render "home/homepage" %>